# Generated by Django 4.2.2 on 2023-06-10 12:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('cite_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('council', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('number_slot', models.IntegerField(blank=True, null=True)),
                ('town', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('cite_type', models.CharField(blank=True, max_length=10, null=True)),
                ('cite_image', models.ImageField(blank=True, default='home/BSD_GreatJones_287.jpg', null=True, upload_to='home')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cite_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('landlord_name', models.CharField(blank=True, max_length=200, null=True)),
                ('landlord_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('landlord_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('landlord_idcard', models.CharField(blank=True, max_length=200, null=True)),
                ('landlord_address', models.CharField(blank=True, max_length=200, null=True)),
                ('landlord_password', models.CharField(blank=True, max_length=200, null=True)),
                ('landlord_username', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('landlord_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tenant_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('tenant_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('tenant_idcard', models.CharField(blank=True, max_length=14, null=True)),
                ('tenant_password', models.CharField(blank=True, max_length=200, null=True)),
                ('tenant_username', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('wardrobe', models.BooleanField(blank=True, null=True)),
                ('air_condition', models.BooleanField(blank=True, null=True)),
                ('dimension', models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=6, null=True)),
                ('light', models.BooleanField(blank=True, null=True)),
                ('water', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('studio_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house.cite')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('wardrobe', models.BooleanField(blank=True, null=True)),
                ('kitchen', models.BooleanField(blank=True, null=True)),
                ('dimension', models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=6, null=True)),
                ('light', models.BooleanField(blank=True, null=True)),
                ('water', models.BooleanField(blank=True, null=True)),
                ('toilet', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house.cite')),
            ],
        ),
        migrations.AddField(
            model_name='cite',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.landlord'),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('number_of_room', models.IntegerField(blank=True, null=True)),
                ('wardrobe', models.BooleanField(blank=True, null=True)),
                ('air_condition', models.BooleanField(blank=True, null=True)),
                ('dimension', models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=6, null=True)),
                ('light', models.BooleanField(blank=True, null=True)),
                ('water', models.BooleanField(blank=True, null=True)),
                ('number_of_bathroom', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('apartment_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house.cite')),
            ],
        ),
    ]
