# Generated by Django 4.2 on 2023-05-05 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="social_github",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[django.core.validators.URLValidator(regex="github.com")],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="social_linkedin",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.URLValidator(regex="www.linkedin.com")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="social_twitter",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[django.core.validators.URLValidator(regex="twitter.com")],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="social_website",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[django.core.validators.URLValidator(regex="http://")],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="social_youtube",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[django.core.validators.URLValidator(regex="youtube.com")],
            ),
        ),
    ]
