# Generated by Django 4.2 on 2023-05-05 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_profile_social_github_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="social_website",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[django.core.validators.URLValidator(regex="https://")],
            ),
        ),
    ]
