# Generated by Django 4.1.5 on 2023-05-07 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_social_stackoverflow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_youtube',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(regex='https://www.youtube.com')]),
        ),
    ]
